apiVersion: v1
kind: Service
metadata:
  name: fizzbuzz-service
spec:
  type: NodePort
  selector:
    app: fizzbuzz
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30036